municipios_amostra = ['Sítio Grande', 'Tasso Fragoso', 'Suzanápolis', 'Botelhos',
                      'Trentin', 'Sananduva', 'Capivari do Sul', 'Prata',
                      'Santo Antônio do Descoberto', 'Santa Mônica',
                      'Santa Fé do Araguaia', 'Lunardelli', 'Perdizes', 'Iguatemi',
                      'General Salgado', 'Cavalheiro', 'Erechim', 'Divisa Nova',
                      'Itapiranga', 'Caibaté', 'Botucatu', 'São José', 'Verê', 'Nazário',
                      'Cerro Negro', 'Aloândia', 'Lourdes', 'Assis',
                      'Alto Paraíso de Goiás', 'Barragem do Itu', 'Grandes Rios',
                      'Curvelo', 'Capão Bonito do Sul', 'Estrela', 'Lindoeste', 'Tanabi',
                      'Barra Funda', 'Santana da Boa Vista', 'Cantagalo', 'Pelotas',
                      'Córrego Danta', 'Lajeado Grande', 'Boqueirão',
                      "Encantado d'Oeste", 'Gaúcha do Norte', 'Carmo de Minas',
                      'Pantano Grande', 'José Boiteux', 'Cruzeiro do Iguaçu',
                      'Itaporanga']